[package]
name = "custom-types"
version = "0.1.0"
authors = ["Kitsu <mail@kitsu.me>"]
edition = "2018"

[dependencies]
diesel = { path = "../../../diesel", version = "2.0.0", features = ["postgres"] }

[[bin]]
name = "custom-types"
path = "src/main.rs"
doc = false
