[package]
name = "all_about_inserts"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
edition = "2018"

[dependencies]
diesel = { version = "2.0.0", path = "../../../diesel", features = ["postgres"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[lib]
doc = false