[package]
name = "all_about_updates"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
edition = "2018"

[dependencies]
diesel = { version = "2.0.0", path = "../../../diesel", features = ["postgres"] }

[lib]
doc = false